### ISSUE TITLE
EVENT: Event (Lager) massenhaft in unterschiedliche Gruppen im Produktivsystem kopieren_Nacharbeiten

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_jubla#103]
Folgeticket zu https://github.com/hitobito/hitobito_jubla/issues/101

Durch Issue https://github.com/hitobito/hitobito_jubla/issues/101 wurde die Lagervorlage https://db.jubla.ch/groups/9539/events/9643 in sämtliche Gruppen der Teilnehmenden aus Anlass db.jubla.ch/groups/1/events/9222/participations kopiert. 
Durch dieses Ticket sollen in den dadurch erstellten Lager noch einige zusätzliche Attribute ergänzt, sowie ein Log der neu erstellten Lager dem Kunden zugestellt werden.

# Nacharbeiten

- Den Coach aus der Vorlage in die Lager Kopien abfüllen (Immer die gleiche Person, für alle Lager)
- Die Datei im Anhang der Vorlage in alle Lager Kopien abfüllen. Alle Anhänge in allen Lagern sind "global sichtbar".
- Flag `event_notify_contact_on_participations` soll bei allen Lagerkopien `value="1"` erhalten. (Aktiviere Flag "Kontakperson über neue Anmeldung per Mail benachrichtigen" bei allen Lagerkopien.)
- label `event_housenumber` soll bei allen Lagerkopien `value="required"` bekommen. (In den Kontaktangaben die Hausnummer als obligatorisches Feld flagen.)
- `event_dates_attributes_0_location`  soll in allen Kurskopien "Wettingen" sein. (Im Register "Daten" das Feld "Ort" mit "Wettingen" befüllen. Bezeichnung bleibt weiterhin leer.)
- Via Supportticket https://help.puzzle.ch/#ticket/zoom/7711 ein Log mit allen ID's der koppierten Events an @richardjubla zustellen

# ToDo
- [x] Coach in allen Lagerkopien abfüllen
- [x] Anhang an alle Lagerkopien anhängen
- [x] Flag "Kontakperson über neue Anmeldung per Mail benachrichtigen" bei allen Lagerkopien aktivieren
- [x] Hausnummer in allen Lagerkopien als obligatorisch anwählen
- [x] Ort mit "Wettingen" abfüllen
- [x] Log an Jubla versenden

**Comment by richardjubla** [comment]
Vielen Dank für die Unterstützung. Von unserer Seite her erfolgreich umgesetzt!
