### ISSUE TITLE
NEJB: Gruppen- und Rollenstruktur für Ehemalige

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito_jubla#129]
Als Projektgruppe Datenbank Ehemaligenwesen
möchten wir einen weiteren Top-Knoten parallel zum aktuellen Top-Knoten haben
um die Ehemaligen dort zu verwalten

Hierfür muss die Gruppen- und Rollenstruktur für Ehemalige ermöglicht werden.

# Tech-Spec

- Gruppen- und Rollenstruktur gemäß nachfolgender Übersicht
- In allen Gruppen des Ehemaligen-Baums sind keine Lager oder Kurse vorhanden
- Epics:
  - #110
  - #122
  - #123

## Struktur

```
* NEJB (Bund)
  * NEJB (Bund)
    * Adressverwaltung: [:group_full]
    * Versandadresse: []
    * IT Support: [:impersonation]
  * Bundesleitung (Bundesleitung)
    * Adressverwaltung: [:admin, :layer_and_below_full, :contact_data]
  * Netzwerk Ehemalige Jungwacht Blauring
    * Leitung: [:group_and_below_full, :contact_data]
    * Adressverwaltung: [:group_and_below_full]
    * Kassier*in: [:group_and_below_read]
    * Aktivmitglied NEJB: [:group_read]
    * Passivmitglied NEJB : [:group_read]
    * Kollektivmitglied NEJB: [:group_read]
    * Neumitglied: []
    * Extern: []
    * Versandadresse: []
* Kanton
  * Kantonaler Ehemaligenverein
    * Leitung: [:group_and_below_full, :contact_data]
    * Adressverwaltung: [:group_and_below_full]
    * Kassier*in: [:group_and_below_read]
    * Mitglied Ehemalige: [:group_read]
    * Neumitglied: []
    * Extern: []
    * Versandadresse: []
* Region
  * Regionaler Ehemaligenverein
    * Leitung: [:group_and_below_full, :contact_data]
    * Adressverwaltung: [:group_and_below_full]
    * Kassier*in: [:group_and_below_read]
    * Mitglied Ehemalige: [:group_read]
    * Neumitglied: []
    * Extern: []
    * Versandadresse: []
* Ehemaligenverein (Schar)
  * Ehemaligenverein
    * Leitung: [:group_and_below_full, :contact_data]
    * Adressverwaltung: [:group_and_below_full]
    * Kassier*in: [:group_and_below_read]
    * Mitglied Ehemalige: [:group_read]
    * Neumitglied: []
    * Extern: []
    * Versandadresse: []
```

# ToDo

- [x] obigen Struktur in einer Datei `structure.txt` speichern
- [x] Struktur mit `rake hitobito:parse_structure` importieren
- [x] ggf. Rake-Task/`StructureParser` konfigurieren oder `structure.txt` anpassen, damit die Datei korrekt eingelesen werden kann
- [x] Gruppen- und Rollenklassen übertragen
- [x] Übersetzungen übertragen
- [x] Specs schreiben, dass keine `Event::Course` oder `Event::Camp` erlaubt sind

**Comment by richardjubla** [comment]
In der Stage-Umgebung sehe ich den Gruppentyp "Ehemaligenschar". Gemäss vorgaben heisst es  Ehemaligenverein (Schar) und * Ehemaligenverein.
![image](https://github.com/user-attachments/assets/2514553e-afa5-4d81-8370-4e0c8aec301c)

**Comment by kronn** [comment]
Ich habe die Übersetzung angepasst, diese ist ab morgen auf der Integration sichtbar.

**Comment by richardjubla** [comment]
Im Top-Knoten Jubla Schweiz kann auf Ebene Kanton und Region der Typ "Schar" erstellt werden. Genau gleich sollte im Top-Knoten NEJB auch auf Ebene Kanton und Region der Typ Ehemaligenverein (Schar) erstellt werden können.

**Comment by richardjubla** [comment]
Aktuelle Rollen in "Einfache Gruppe" Global
```
* Global
  * Einfache Gruppe
    * Leitung: [:group_full]
    * Mitglied: [:group_read]
    * Adressverwaltung: [:group_full]
    * Ehemalig: [:group_read]
    * Extern: []
    * Versandadresse: []
```

**Vorschlag für Rollen in "Einfache Gruppe" (Ehemalige)  (global im Top-Knoten NEJB)**
```
*  NEJB
  * Einfache Gruppe (Ehemalige)
    * Leitung: [:group_full]
    * Adressverwaltung: [:group_full]
    * Mitglied Ehemalige: [:group_read]
    * Neumitglied: []
    * Extern: []
    * Versandadresse: []
```

Begründung: Die Rollen und Berechtigungen der globalen einfachen Gruppe werden übernommen und um die spezifischen Rollen eines Ehemaligenverein angepasst. Dies gilt als Grundalge für "alle Bedürfnisse" welche im Knoten so abgeleitet werden könnten. Auf die Rollen Aktiv-/Passivmitglied wird bewusst verzichtet. 
@nicole-schlemmer

**Comment by richardjubla** [comment]
Fehler: Aktuell ist die Rolle Adressverwaltung in Einfache Gruppe (Ehemalige) falsch:
![image](https://github.com/user-attachments/assets/16126841-1396-4d8f-ad5d-5f1caefd8a3b)

Ohne Berechtigungen in der Gruppe wäre sie nicht selbstverwaltbar und nicht gemäss Vorschlag.

**Comment by kronn** [comment]
> In der Gruppe Einfache Gruppe (Ehemalige) fehlt die Rolle Extern:

Die Rolle ist vorhanden, allerdings nur sichtbar, wenn man in dieser Gruppe bereits Rechte hat. Diese Einstellung (not visible from above) entspricht den Externen in den anderen Gruppen der Jubla.
