### ISSUE TITLE
Elternzugang/Jublasurium

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#132]
Hier werden alle relevanten Informationen und Stories im Zusammenhang mit dem Jublasurium/Elternzugang aufgelistet.

 **Awareness/Priorität**

Bis zum Anmeldeschluss der 2. Phase des Jublasurium werden alle Ressourcen in dieses Ticket (Elternzugang/Jublasurium) gelenkt. Bei Bedarf folgt ein "Jubla-Release" nach dem 21.10.24. Das Inkrement 4/24 wird dahingehend angepasst.

**Stories/Themen**
- [x] Awareness/Priorität kommunizieren **Erfolgt**
- [x] Rolle Kind anpassen https://github.com/hitobito/hitobito_jubla/issues/146  **im Inkrement 4/24**
- [x] EVENT: Anmeldebestätigung (PDF) in Hitobito [#85](https://github.com/hitobito/hitobito_youth/issues/85) - **Auf Produktiv-Umgebung, testen durch Jubla**
- [x] Anforderungen an Anmeldeschluss intern klären

**Support**
- [x] Abklären von Ausfall über Helpdesk Ticket#368330 - **Erledigt**
- [x] Klären der Zuteilung/Anmeldung auf "fremde" Scharen/Lager über Helpdesk Ticket#367699 - **Erledigt**
- [x] Auftrag: Massemutation Anmeldeschluss setzten / Anmeldung schliessen #136  Ticket#368346 - **Go bei Jubla, Umsetzung möglich**

**Comment by richardjubla** [comment]
- Gemäss Inspektion der Log-Files gingen keine Jublasurium Lageranmeldungen verloren. 
- Eine Schar wurde darüber Informiert, dass die Anpassung der Informationen von ihrer Jublasurium Lageranmeldung zurückgesetzt wurde

**Comment by richardjubla** [comment]
Anmeldeschluss der 2. Phase des Jublasurium erfolgreich abgeschlossen.
