### ISSUE TITLE
NEJB - S7: Release ausführen

### ISSUE THREAD

**Issue by tobiasstern** [hitobito/hitobito_jubla#169]
Im Rahmen des Release am 14. Januar mit den den neuen Funktionen, braucht es vom Software Engineering eine Begleitung und Koordination der diversen Vor- und Nachbearbeitungen.

Ein Teil davon verrechnen wir über das übliche Wartungs-Budget und der Teil hier über das NEJB-Budget.

## ToDos

- [x] FeatureGate `groups.nejb` vor dem Deployment aktivieren
- [x] `rake nejb:insert_new_root` nach dem Deployment ausführen, um den gemeinsamen Root-Knoten "hitobito" hinzuzufügen.
- [ ] Gruppenstruktur anlegen (Aufgabe NEJB/Jubla)
- [x] `rake nejb:flock_alumnus_groups:consolidate` um mehrfache "Ehemalige"-Gruppen zusammenzufassen
- [x] `rake nejb:flock_alumnus_groups:rename` um "Ehemalige"-Gruppen zu "Ausgetretenen Leitungspersonen" umzubenennen
- [x] ~`rake nejb:other_alumnus_groups:remove_members` um Mitglieder in "Ehemaligen"-Gruppen oberhalb der Scharebenen zu entfernen.~

**Comment by tobiasstern** [comment]
Gemäss Besprechung am 09.01. Okay

**Comment by richardjubla** [comment]
Notizen für mich:

- Gemäss Besprechung OK - Go für Release
- S7 Einzelfälle von "Ehemalige"-Gruppen zu "Ausgetretenen Leitungspersonen" zusammenfassen
- S7 Entscheid: Mitglieder oberhalb der Scharen NICHT löschen (Konsequenz: Ehemalige bleiben oberhalb der Scharen bestehen)



Meeting 9.1.25
- Blocker gelöst: Zusammenfassen und Entfernen von alumnus_gruppen aus S7 nicht umsetzen. (Nicht vorbereiteter, kommunizierter Eingriff in Gruppenautonomie) https://github.com/hitobito/hitobito_jubla/issues/169#issuecomment-2575647738 

- Verständnis für Beheben und Prüfen von Fehlern bei Rollen:  Wir haben mehrere Hinweise zurückgemeldet, dass Rolle(n) und Gruppen/Ebenen (für ehemalige Jubla-Mitglieder / im Top-Knoten Ehemalige) nicht korrekt funktionieren, falsch dargestellt werden oder ihre Berechtigungen falsch sind. Wir erwarten hier mehr Sicherheit und Tests um das korrekte Verhalten und Darstellung (inkl. Asside/Profil) zu garantieren. Wir halten es für essenziell, dass alles ohne Fachwissen und gemäss Dokumentation nachvollziehbar Funktioniert (siehe DoD S1). Das muss für die jubla.db Benutzer*innen korrekt und intuitiv funktionieren!

- Aufmerksamkeit für Profile "ohne Rollen". Ein Vorstand (Rolle Leitung) muss in der Lage sein, Profile in seiner Ebene (Verein) aus allen Rollen zu entfernen und das Profil in "ohne Rollen" zu finden. Ein Profil muss in der letzten Gruppe/Ebene in ohne Rollen landen, in der es die letzte Rolle hatte. (Adressverantwortung) 
(Aktuell gehen wir davon aus, dass es so funktioniert, wollen uns aber sehr sicher sein! Erkenntnis: Informationen zu Profil ohne Rollen in Suchtreffer ist sehr eingeschränkt, da die Informationen zur Zugehörigen "ohne Rollen Gruppe" fehlen. Es sit sichergestellt, dass Profile nicht "verschwinden".)

- Wunsch von "FG Datenbank" nach Release / Projektabschluss platziert: Sauber abschliessen! Feature und Dokumentation für langfristigen Betrieb und Weiterentwicklung oder bugfixes in der Verantwortung von Puzzle/NEJB sicherstellen. Der NEJB ist weiterhin der Partner und zuständig für sein Feature. Puzzle/Hitobito regelt stabile Einbettung und Übergabe in langfristigen Betrieb.

**Comment by kronn** [comment]
Unsere o.g. Aufgaben zum Release sind erledigt. Die Gruppenstruktur des NEJB kann angelegt werden.

**Comment by richardjubla** [comment]
**Sammlung von Notizen nach dem Release für Release Besprechung am 16.01.2025**
(laufend ergänzt, relevant erst am 16.1.)

- Bug: Die Rolle Mitglied im Gruppentyp Fachgruppe wird im Filter Austritte angezeigt
- Bug: Die Rolle Mitglied im Gruppentyp Bundesleitung wird im Filter Austritte angezeigt
- Empfehlung: Alle Rollen und Filter im Zusammenhang mit "Austritte" überprüfen
- Organisatorisches: Von der Jubla hat noch niemand Rechte in "hitobito"
- Hinweis: Für NEJB,  Handbuch ist  aktualisiert
