### ISSUE TITLE
Rollen in Kursen und deren Qualifikationsverlängerung (NDS)

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#33]
**User-Story**
>Als Leitung der FG Datenbank möchte ich den korrekten Datenabgleich zischen der NDS und der jubla.db ermöglichen. Dazu nehme ich die Anforderung/Input von Remo (Aus- & Weiterbildung) auf.
Im Herbst 2022 wird die neue Nationale Datenbank für Sport (NDS) ihren Betrieb aufnehmen und damit die SPORTdb ablösen. Neu haben nicht nur die J+S-Coachs ein Login, sondern auch alle J+S-Leiterinnen und -Leiter, J+S-Expertinnen und -Experten. 
Zwischen der jubla.db und der NDS werde dazu Daten ausgetauscht (manueller Export/Import).
Für die Korrekte Übertragung der Qualifikationsverlängerungen sind nun anpassungen an den Rollen notwendig. Die Rolle «Helfer/-in» ist neu für Personen vorgesehen, welche mindestens 6h Kadertätigkeit ausüben. Die Rolle «Referent/-in» für weniger als 6h Kadertätigkeit.
Im Bereich «Qualifikationen» sollen deshalb neu nebst Hauptleitung und Leitung auch «Helfende» angezeigt werden, um ihnen automatisch (durch Klick auf den Haken) die Qualifikationen zu verlängern.

---
**Aspekte**
- Die Rolle «Helfer\*in» legen wir neu so aus als eine Person, welche im Kurs mindestens 6h Kadertätigkeit ausübt.
- Die Rolle «Referent\*in» legen wir neu so aus als eine Person, welche weniger als 6h Kadertätigkeit ausübt.

a
- Im Bereich «Qualifikationen» sollen deshalb neu nebst Hauptleitung und Leitung auch «Helfende» angezeigt werden, um ihnen automatisch (durch Klick auf den Haken) die Qualifikationen zu verlängern.

**Definition of Done**
-  Qualifikationsverlängerung für Rollen «Helfer\*in»
- Anpassen der Rolle gemäss geschlechtergerechter Kommunikation in der Jubla -> «Helfer\*in» und «Referent\*in» 
- Korrekte Übertragung der Qualifikationsverlängerungen in die NDS ist möglich
- Änderung durch (Aus- & Weiterbildung) dokumentiert
- Rollen und ihre Abhängigkeiten geklärt (Siehe Frage zur Absicherung)
- Release in Sprint Q3 umgesetzt

---

**Hintergrund:**
In der neuen NDS gibt es neu die Rolle Drittperson. Dies sind alle bisherigen Rollen wie z.B. Kurshelferin, Referentin, Küchenteam, welche mindestens 6h Kadertätigkeit ausüben. Wir (Pfadi, Cevi, Jubla) haben vereinbart, dass wir bspw. Küchenteam oder Referent*innen für 2-Stunden-Blöcke nicht in die NDS übertragen, sondern nur ab 6 Stunden Kadertätigkeit. Diese Personen (ab 6h) sollen dann auch über unsere Datenbank eine Anerkennungsverlängerung erhalten. Deshalb brauchen wir eine Unterscheidung der Rolle einer Person mit weniger als 6h Kadertätigkeit und mehr als 6h Kadertätigkeit

**Zeithorizont:**
Umsetzung soll bis am 1. November erfolgen, da ab dann Referent/-innen und Helfer/-innen den Kursen 2023 hinzugefügt werden.

**IST-Zustand:**
Ein Jubla-Kurs kennt die folgenden 6 Rollen: Hauptleitung, Leitung, Küche, Helfer/-in, Kassier, Referent/in. Die Rolle Hauptleitung und Leitung erhält eine Qualifikationsverlängerung (falls in der Kursart so eingestellt).

**SOLL-Zustand:**
Die Rollen an sich können beibehalten werden.
Die Rolle «Helfer/-in» legen wir neu so aus als eine Person, welche im Kurs mindestens 6h Kadertätigkeit ausübt.
Die Rolle «Referent/-in» legen wir neu so aus als eine Person, welche weniger als 6h Kadertätigkeit ausübt.

Im Bereich «Qualifikationen» sollen deshalb neu nebst Hauptleitung und Leitung auch «Helfer/innen» angezeigt werden, um ihnen automatisch (durch Klick auf den Haken) die Qualifikationen zu verlängern.

**Frage zur Absicherung:**
Sind wir korrekt in der Annahme, dass aktuell die Rolle «Referent/in» und «Helfer/in» keine Unterschiede haben – ausser, dass Referenten in den BSV-Angaben und im BSV-Export separat ausgewiesen werden?

### Tech-Details

- Wird im `Event::QualificationsController` behandelt. Das meiste ist im Core mit wenigen Erweiterungen im Jubla-Wagon

## ToDo

- [x] Umsetzung im Youth-Wagon oder wo nötig in den einzelnen Wagons (pbs, jubla, cevi, sjas?)
- [x] Sicherstellen, dass bei PBS, Cevi, Jubla in Kursen Rollen für "Helfer*in" und "Referent*in" existieren (allenfalls erstellen oder Übersetzungen anpassen)
- [x] Personen mit Rolle "Helfer*in" auf dem Qualifikationen-Tab anzeigen, sodass ihre Qualifikation dort am Ende des Kurses verlängert werden kann
  - [x] Controller anpassen, neu auch Helfer-Rollen qualifizieren
- [x] Specs schreiben
- [x] mit angemessener Rolle durchklicken
- [x] CHANGELOG-Eintrag unter unreleased unten ergänzen

**Comment by richardjubla** [comment]
Lieber @thomasEllenberger bitte dieses Issue/Story nach Möglichkeit auch für den Sprint Q3 vorsehen.

**Comment by richardjubla** [comment]
Fehler: Anpassen der Rolle gemäss geschlechtergerechter Kommunikation in der Jubla -> «Helfer*in» und «Referent*in» wurde nicht gemacht.

**Comment by richardjubla** [comment]
Rückmeldung:
Antwort auf Frage (Unterschiede Rolle Referent*in) wurde nicht beantwortet.
![image](https://user-images.githubusercontent.com/95908537/192751135-499e9c8e-e6a5-40f7-92ec-07a350df2e31.png)

**Comment by mtnstar** [comment]
> Fehler: Anpassen der Rolle gemäss geschlechtergerechter Kommunikation in der Jubla -> «Helfer_in» und «Referent_in» wurde nicht gemacht.

habe gerade auf der Integrationsumgebung geprüft und dort werden die Rollen geschlechtergerecht Dargestellt:

![image](https://user-images.githubusercontent.com/655627/193781494-6deb0693-708f-4f03-ae37-12fe7ff76b54.png)

Haben wir evtl. einen Ort übersehen wo es nicht richtig angezeigt wird?

**Comment by mtnstar** [comment]
> Rückmeldung: Antwort auf Frage (Unterschiede Rolle Referent*in) wurde nicht beantwortet. ![image](https://user-images.githubusercontent.com/95908537/192751135-499e9c8e-e6a5-40f7-92ec-07a350df2e31.png)

wenn sich die Frage auf die Berechtigungen bezieht, dann ja. Beide haben die Permission :participations_read und können somit die Teilnehmerinfos lesen bei Kursen wo sie selber Teilnehmer sind.

**Comment by ThomasEllenberger** [comment]
> > Fehler: Anpassen der Rolle gemäss geschlechtergerechter Kommunikation in der Jubla -> «Helfer_in» und «Referent_in» wurde nicht gemacht.
> 
> habe gerade auf der Integrationsumgebung geprüft und dort werden die Rollen geschlechtergerecht dargestellt:
> 
> ![image](https://user-images.githubusercontent.com/655627/193781494-6deb0693-708f-4f03-ae37-12fe7ff76b54.png)
> 
> Haben wir evtl. einen Ort übersehen wo es nicht richtig angezeigt wird?

Denke es geht darum das die Jubla eine andere Schriftweise wünscht.
Referent*in anstelle von Referent/-in
Helfer*in anstelle von Helfer/-in

Korrekt, @richardjubla ?

**Comment by richardjubla** [comment]
> Denke es geht darum das die Jubla eine andere Schriftweise wünscht. Referent_in anstelle von Referent/-in Helfer_in anstelle von Helfer/-in
> 
> Korrekt, @richardjubla ?

Die korrekte Schriftweise wäre `Helfer*in`  und `Referent*in`

Ich habe hier die automatische git-Textformatierung übersehen und wohl Verwirrung gestiftet. Aus `«Helfer*in»` wird hier «Helfer*in» «Helfer*in» . Ursprünglich war es korrekt.


Hintergrund:
In Jungwacht Blauring nehmen wir unsere gesellschaftliche Mitverantwortung wahr, die wir als Kinder- und Jugendverband bei Geschlechterthemen haben. In unseren Texten achten wir deshalb auf geschlechtergerechte Kommunikation. Konkret sollen auch bei aktualisierungen der Datenbank jeweils die Texte aktualsiert werden.

https://mitglieder.jubla.ch/mitglieder/themen/gender/

**Comment by richardjubla** [comment]
@ThomasEllenberger 
**Wir sind mit Testen durch. Es gab keine zusätzlichen Rückmeldungen.** 
Die beantworte Frage werde ich noch aufnehmen. Offen ist noch die Anpassung der Schriftweise.
