### ISSUE TITLE
Release Version 1.30

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#49]
**User-Story**

Als jubla möchten wir zusammen mit Puzzle/Hitobito den Release Version 1.30 auf der produktiven Datenbank auszuliefern.

Geplant ist ein Release am 24.10.23

**Aspekte**

- Gesamter Changelog ist abgenommen, geprüft und freigegeben
- Zwingende Projekte im Changelog (Kursverwaltung) sind abgeschlossen und auf dem Testsystem abgenommen, geprüft und freigegeben. (Alternativ werden Features ausgekoppelt, deaktiviert oder ähnlich)
~~- Alle im Inkrement (4/23) vorgenommenen Arbeiten sind auf dem Testsystem abgenommen oder in einem geklärten Status für einen Release.~~
- Der Termin für den Release ist vorgängig gemeinsam festgelegt und abgeglichen mit den restlichen Arbeiten und Aufgaben

**Definition of Done**

- [x]  Gesamter Changelog ist abgenommen, geprüft und freigegeben
- [x]  Changelog ist beschrieben und öffentlich Kommuniziert (Aufgabe von jubla)

Version 1.28
- [x] Neu gibt es eine Option, um die Mailadressen von Personenlisten in einem Format spezifisch für Outlook zu exportieren. Merci [@simfeld](https://github.com/simfeld)! [(#2043)](https://github.com/hitobito/hitobito/issues/2043)
- [x] Diverse Verbesserungen bei Anlass-Einladungen. Personen die im ganzen Layer Berechtigungen haben, können auch in Anlässen des ganzen Layers andere Personen einladen. Ein neuer Hinweis erklärt, dass die Einladungen nicht per Mail versendet werden. Einladungen können neu sortiert und gelöscht werden, dafür nicht mehr doppelt erfasst. Wenn man eine Einladung ablehnt, wird einem das weiterhin zur Information angezeigt. Merci [@nchiapol](https://github.com/nchiapol)! (#2045, #2051)
- [x] Tags auf Anlässen können jetzt von denselben Personen entfernt werden, die sie auch erfassen können. Merci [@davudevren](https://github.com/davudevren)! [(#2050)](https://github.com/hitobito/hitobito/issues/2050)
- [x] Das Profilbild einer Person kann neu via Klick gross angezeigt werden. Merci [@bergerar](https://github.com/bergerar)! [(#2044)](https://github.com/hitobito/hitobito/issues/2044)
- [x] Die Rechnungsliste einer Sammelrechnung zeigt neu standardmässig nicht mehr Rechnungen vom aktuellen Jahr, sondern alle Rechnungen seit Erstellung der Sammelrechnung an. Merci [@lukas-buergi](https://github.com/lukas-buergi)! [(#2047)](https://github.com/hitobito/hitobito/issues/2047)
- [x] Die Zwei-Faktor-Authentisierung ist jetzt etwas kulanter, wenn man den Code knapp zu spät eingibt, sowie bei der Verwendung von Hardware OTP Keys. Merci [@cleverer](https://github.com/cleverer)! [(#2052)](https://github.com/hitobito/hitobito/issues/2052)
- [x] Die Ansicht um Zwei-Faktor-Authentisierung einzurichten wurde für Mobile optimiert, und man kann die Zwei-Faktor-Authentisierung jetzt auch einrichten, ohne den QR-Code zu scannen, indem man das Secret kopiert. Merci [@TeamBattino](https://github.com/TeamBattino)! [(#2046)](https://github.com/hitobito/hitobito/issues/2046)
- [x] Rollen können neu als self.basic_permissions_only = true markiert werden. Dies führt zu eingeschränkten Ansichten und Berechtigungen für die betroffene Person (sww#120)
- [x] Die E-Mail, welche bei der "Passwort vergessen" Funktion gesendet wird, ist neu übersetzt.
- [x] Geburtstag und Geschlecht tauchen nicht mehr doppelt im "Spaltenauswahl"-Export von Personenlisten auf
- [x] Fonts werden direkt von Hitobito ausgeliefert [(#1632)](https://github.com/hitobito/hitobito/issues/1632)
- [x] Die Vorbedingungen einer Kursart können neu als "Muss gültig sein" oder "Muss gültig oder weggefallen sein" deklariert werden. Wenn die Vorbedingung gültig sein muss verhält es sich wie bisher, bei gültig oder weggefallen muss der Teilnehmer die Qualifikation der Vorbedingung besitzen oder jemals besessen haben. Dies gilt unabhängig von der Gültigkeit oder Reaktivierbarkeit der besagten Qualifikation. [(#1640)](https://github.com/hitobito/hitobito/issues/1640)
- [x] Neuer Personentab "Sicherheit", welcher Informationen und Vorgänge zu Sicherheitsmassnahmen aufzeigt und das Passwort einer Person zurücksetzen lässt (benötigt :update Permission auf Person) [(#1688)](https://github.com/hitobito/hitobito/issues/1688)
- [x] Neu können mittels "Buchungsbeleg" Tab bei den Rechnungen die Zahlungen in einem definierbaren Zeitrahmen ausgewertet werden. So werden die Zahlungen ihren Rechnungsartikeln zugeordnet und aufsummiert [(hitobito_sww#39)](https://github.com/hitobito/hitobito_sww/issues/39)
- [x] Anmeldungen für öffentlich sichtbare Anlässe verbessert [(#1775)](https://github.com/hitobito/hitobito/issues/1775)
- [x] Für variable Spendenaufrufe wird neu der Median über alle Zahlungen im definierten Zeitraum verwendet [(hitobito_die_mitte#204)](https://github.com/hitobito/hitobito_die_mitte/issues/204)
- [x] Der Buchungsbeleg kann neu zu XLSX oder CSV exportiert werden [(hitobito_sww#61)](https://github.com/hitobito/hitobito_sww/issues/61)
- [x] Rechnungen können mit Firmennamen gefiltert werden [(#1773)](https://github.com/hitobito/hitobito/issues/1773)
- [x] Personen mit :finance Berechtigung können neu bei allen Personen in und unterhalb ihrer Ebene die Rechnungen der Person mittels "Rechnungen" Tab auf dem Profil anzeigen lassen. [(hitobito_die_mitte#205)](https://github.com/hitobito/hitobito_die_mitte/issues/205)
- [x] In der Kursansicht können neu alle Kurse welche "Anlass ist für die ganze Datenbank sichtbar" aktiviert haben, gefunden werden. [(#1813)](https://github.com/hitobito/hitobito/issues/1813)
- [x] Rechnungsempfänger auf QR Rechnungen wird validiert: muss genau 3 Zeilen enthalten [(#1825)](https://github.com/hitobito/hitobito/issues/1825)
- [x] Erweiterung Personenfilter [(#295)](https://github.com/hitobito/hitobito/issues/295) Filterung von Personenlisten nach Alter, Geburtsdatum und Geschlecht (merci [@simfeld](https://github.com/simfeld)!)
- [x] Neue Filterbedingung "Enthält nicht" [(#295)](https://github.com/hitobito/hitobito/issues/295)
- [x] OAuth Applikationen können neu spezifischen Zugriff auf nur einzelne API-Endpoints bekommen. Zur Auswahl stehen die Endpoints "group", "person", "event", "mailing_list" und "invoice". (#1399, merci [@simfeld](https://github.com/simfeld)!)
- [x] Wird die API mit einem Service Token benutzt, dann kommen jetzt dieselben Felder auf der Person wie mit der veralteten User Authentication (#1460, merci [@sniederberger](https://github.com/sniederberger)!)
- [x] Bei Zugriffsfehlern in der JSON API wird jetzt konsistent ein JSON-Payload zurückgegeben, statt wie bisher eine HTML-Seite (Seiteneffekt von #1866, ursprünglich gemeldet in der [erweiterten Fehlerliste](https://gist.github.com/carlobeltrame/8dd5b5e6279d91d1e3c181cb9086666a#x-api-should-always-return-json-and-return-the-same-for-parameters-style-and-headers-style-calls) bei der [Einführung der Service Tokens](https://github.com/hitobito/hitobito/issues/586))
- [x] Der API Endpoint eines einzelnen Events enthält neu die URL von Anhängen [(#1873)](https://github.com/hitobito/hitobito/issues/1873)
- [x] Neues "Hitobito Log" einsehbar mit admin permissions unter "Einstellungen" [(#1840)](https://github.com/hitobito/hitobito/issues/1840)
- [ ] Neues Bestätigungsmail für Event Voranmeldung [(hitobito_cevi#80)](https://github.com/hitobito/hitobito_cevi/issues/80)
- [x] Einführung neue JSON:API für Personen [(#1920)](https://github.com/hitobito/hitobito/issues/1920)
- [x] Neu kann in den Rechnungseinstellungen im Tab "E-Mail" der Absendername definiert werden, mit dem die Rechnungen dieser Ebene versendet werden [(#1893)](https://github.com/hitobito/hitobito/issues/1893)
- [ ] Neu kann auf einer Ebene eine Datenschutzerklärung (DSE) hinterlegt werden. Diese muss, falls vorhanden, bei der Selbstregistrierung, dem Anmelden bei einem Anlass/Kurs oder dem Hinzufügen einer Person auf einer Gruppe akzeptiert werden um fortzufahren. [(#1881)](https://github.com/hitobito/hitobito/issues/1881)
- [x] Personen mit layer_full oder layer_and_below_full können neu Personen, welche in ihren Ebenen unter "Ohne Rollen" erscheinen, per globale Suchfunktion finden und anzeigen. [(hitobito_sww#80)](https://github.com/hitobito/hitobito_sww/issues/80)
- [x] Anbindung an Nextcloud möglich [(#1854)](https://github.com/hitobito/hitobito/issues/1854)
- [x] Rechnungen werden neu in einem Hintergrundprozess gedruckt [(#2014)](https://github.com/hitobito/hitobito/issues/2014)
- [x] Auf dem Buchungsbeleg sind die einzelnen Positionen nun verlinkt und führen auf eine Auflistung aller Rechnungen, welche die jeweilige Position beinhalten [(hitobito_sww#69)](https://github.com/hitobito/hitobito_sww/issues/69)
- [ ] Es können neu bei einer Person entweder Verwalter*innen oder Kinder hinterlegt werden. [(#1965)](https://github.com/hitobito/hitobito/issues/1965)
- [x] Der BSV-Export berücksichtigt jetzt gemäss den neuen BSV-Regeln alle Personen unter 30 Jahren (statt wie zuvor nur zwischen 17 und 30 Jahren). Merci [@Michael-Schaer](https://github.com/Michael-Schaer)! (hitobito/hitobito_youth#27, hitobito/hitobito_pbs#265)
- [x] NDBJS und SportDB Exporte wurden entsprechend der neuen NDS ersetzt [(#1733)](https://github.com/hitobito/hitobito/issues/1733)
- [x] Coaches auf Lager haben neu die Berechtigung um den Sportdb Export für die Teilnehmer zu erstellen
Helfer/-innen eines Kurses werden neu nach Abschluss des Kurses im Tab "Qualifikationen" angezeigt. Dort können ihnen dann die Qualifikation ausgestellt werden [(hitobito_jubla#33)](https://github.com/hitobito/hitobito_jubla/issues/33)
- [x] Kursrollen sind neu mittels Genderstern geschrieben [(#1896)](https://github.com/hitobito/hitobito/issues/1896)
- [x] Neue Lagerübersicht "Lager" in der Hauptnavigation. IT Support & Mitglieder in der Bundesleitung sehen alle Lager von heute bis in vier Wochen. Coaches und Leiter der Addressverwaltung oder eines Kantons sehen alle Lager des aktuellen Jahres in ihrem Kanton. [(#1758)](https://github.com/hitobito/hitobito/issues/1758)

**Comment by richardjubla** [comment]
Changelog (Kommunikation) für jubla ist bereit: https://jubladb-handbuch.readthedocs.io/de/latest/changelog-news.html#release-version-1-30-24-10-2023

**Comment by richardjubla** [comment]
@ThomasEllenberger 

Gesamter Release getestet.


Noch offen oder mit Bemerkungen/Hinweisen:

 https://github.com/hitobito/hitobito/issues/1881 - Wollten wir eigentlich rechtzeitig für unseren Wagon mit #50 anpassen. Kann/Muss aber auch so gehen.
https://github.com/hitobito/hitobito_cevi/issues/80 - Bitte noch Frage(n) beantworten
https://github.com/hitobito/hitobito/issues/1965 - Dieses Feature muss mit Release auf Produktiv deaktiviert oder fertig sein (Memo an mich)

**Comment by richardjubla** [comment]
> @richardjubla
> 
> Danke für die Rückmeldung. Wir gehen somit davon aus dass dem Release am 09. Januar 2024 nichts im Wege steht. Wie bereits informiert gibt es aus unserer Sicht hier diesmal keine Möglichkeit mehr den Release erneut zu verschieben. Wir wollen die Jubla Umgebung unbedint auch auf den neusten Codestand heben.
> 
> Betreffend cevi#80: Dieses Ticket lief auch für uns leider nicht wie gewünscht. Hier hat man während der Umsetzung mehrmals die Ziele geändert. Ohne tiefer in den Code zu schauen (Deutlicher Mehraufwand) können wir desshalb aktuell nicht mehr sagen welche Teile wo umgesetzt wurden. Wir haben bereits nach der Umsetzung des Tickets unsere Lessions Learned daraus gezogen, so dass dies in dieser Form nicht mehr vorkommen sollte. Was das Changelog angeht: Das ist durchaus realistisch dass ihr hier verschiedene Features unter 1.28 hattet... eines kann 1.28.xx und das andere 1.28.xy sein... Dieses Problem haben wir mit den regelmässigen Releases und der neuen Semantischen Versionierung welche wir ab nächstem Jahr haben behoben.

Ja, ein Release am 09. Januar 2024 ist weiterhin als Ziel gesetzt. Gesamter Changelog ist abgenommen, geprüft und freigegeben!  In der Zwischenzeit passiert ja aber noch mit #52 etwas. 
Auf die Lessions Learned werden wir noch definitiv zurückkommen wenn wir die Kursverwaltung wieder hervor nehmen. 

Story kann mit Release geschlossen werden.

**Comment by kronn** [comment]
Viel Freude mit Version 2.0.0 :-)
