### ISSUE TITLE
EVENT: Verwalter*innen-Beziehung in Event nutzbar/sichtbar machen

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#78]
Dieses Feature folgt auf https://github.com/hitobito/hitobito_jubla/issues/75 und nimmt Bezug auf https://github.com/hitobito/hitobito_jubla/issues/75#issuecomment-1944083248
Es geht davon aus, dass #77 umgesetzt wird oder wurde. 

Als Mensch der einen Event verantwortet, durchführt, verwaltet, coacht oder ähnlich, möchte ich den Status der Verwalterinnen-Beziehung jederzeit überprüfen und in der Anmeldung sehen können um zu wissen, ob das Profil verwaltet wird (Verwalterinnen hat) oder es Kinder verwaltet.

**Neu soll in einer Event-Anmeldung der Wert  der Verwalterinnen-Beziehung «Kind» (person_people_manageds) und «Verwalter*innen» (person_people_managers) **immer** in der Anmeldung (inkl. PDF) sichtbar sein. Den Event-Verantwortlichen (Scharleitung, Coach, Hauptleitung, Leitung, Lagerleitung, Kontaktperson, etc, evtl. analog Administrationsangaben) soll dann immer mindestens der volle Name sichtbar sein (selbst wenn die Berechtigungen dazu fehlen!).** 

Umsetzung im Youth-Wagon (oder Jubla-Wagon). Platzieren der Werte person_people_manageds und person_people_managers in PDF-Anmeldungen individuell je Wagon.

Beispiel: Der Vater Baumann meldet Sohn 1 Baumann (beide sind Mitglied in der Jungwacht Baden) für einen Anlass beim Blauring Baden an. Die Leitung (Leiterin Blauring Baden) für den Anlass muss in der Anmeldung von Sohn 1 sehen, dass dieser als Verwalter den Vater Baumann eingetragen hat. Je nach individueller Entscheidung kann der Blauring Baden die Anmeldung so belassen oder dafür besorgt sein, dass Vater Baumann noch eine Rolle im Blauring Baden bekommen muss damit Sohn 1 an diesem Anlass teilnehmen kann. (Damit bei einem Notfall der Blauring Baden die Informationen von Vater Baumann hat)

Beispiel 2: Der Vater Hermann meldet Tochter 1 für einen öffentlichen Kurs vom Kanton Luzern an. Die Kursadministration, die Kursleitung und der Coach sehen, dass Vater Hermann der Verwalter von Tochter 1 ist und es demnach ein Profil von Vater Hermann gibt. 

Abgrenzung: Wir müssen uns bewusst sein, dass mit diesem Feature das Vorhandensein, der Status der Verwalter*innen-Beziehung inklusive des Namen, mit den Event-Verantwortlichen geteilt wird. Die Notwendigkeit ergibt sich aus der Verantwortung der Event-Verantwortlichen diese Information entweder immer ohne Anhaltspunkte zu vermuten oder zusätzlich abzufragen (zu müssen). Einer Verwalter*in oder einem Kind ist nämlich nicht bewusst, dass eine Event-Anmeldung keinerlei Hinweise oder Informationen über eine Verwalter*innen-Beziehung übermittelt. Ähnlich ist es mit der Rolle "Extern" oder "Kind" welche lediglich in der gleichen Ebene/Gruppe sichtbar ist und sich für einen Event anmeldet: Die Anmeldung (Event-Informationen) werden durch die Anmeldung im Event für alle relevanten oder eingestellten Profile/Rollen sichtbar. 

Vorteil/Absicht: Ein Verein/Ebene/Gruppe kann so öffentliche Event-Anmeldungen ermöglichen, ohne zwingend alle Verwalter*innen-Beziehung mit Abfragen oder dem vergeben von Rollen absichern zu müssen. 

# Mockup

Mockup für eine Event-Anmeldung in welchem die Informationen der Verwalter*innen-Beziehung als Anmelde-Informationen mit der Anmeldung gespeichert werden. Dies ist teilweise (je nach vorhandenen Rechten) bereits der Fall. Neu sollen aber alle Event-Verantwortlichen Profile (Event-Leitung etc.) und Rollen (Scharleitung) diese Informationen sehen. 
![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/0dc343c9-d37e-4272-a911-08e0fe1f8a68)
![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/15e4113a-12f0-41e5-9508-3568d7013982)

Beispiel einer Lagerandmeldung (PDF) in welcher die Verwalter*innen-Beziehung ersichtlich ist. Damit ist der Lagerleitung klar, dass "VN Verwalter*in jubla nölli Mutter" (Vorname Name der Verwalter*in) die Kontrolle über das Profil hat und demzufolge eine Mitverantwortung über diese Anmeldung hat:

<img width="1009" alt="image" src="https://github.com/hitobito/hitobito_jubla/assets/95908537/2070d78c-c640-4df0-b3e2-bfd44c0edddc">

Begründung:
Die Sichtbarkeit/Darstellung der Verwalter*innen-Beziehung erscheint als notwendiges Mittel, damit ein Verein/Gruppe/Ebene mit Verwalterinnen-Beziehung irgendwie umgehen kann. Damit keine Rollen/Mitgliedschaften vergeben werden müssen, soll die Verwalterinnen-Beziehung "lediglich" sichtbar gemacht werden. Wir sehen ein, dass das vergeben von Rollen oder das erweitern der Berechtigungen über Events/Selbstregistrierung eine komplexes Unterfangen mit möglichen Nebenwirkungen sein könnte.
Die Scharen/Event-Verantwortlichen könnten dann bereits sehr umfangreich ihre Verantwortung wahrnehmen: Sofern es ein Mitglied/Anmeldung/Interessent mit unklaren Verwalter*innen-Beziehung gibt, kann reagiert werden und diese Beziehung "geklärt" werden.

# Akzeptanzkriterien:

- Event-Verantwortliche oder Event-Durchführende haben die Verantwortung und Einsicht über die Verwalter*innen-Beziehung aller Anmeldungen.
- Die Implementierung stellt eine reale Zeitersparnis und Mehrwert für den Verein, da er die Verwalter*innen-Beziehung bei Anmeldungen nicht mehr vermuten oder explizit überprüfen muss.

Defintion of Done

- Alle Akzeptanzkriterien wurden erfüllt oder eine alternative gefunden
- Die Implementierung wurde getestet und als fehlerfrei bestätigt.
- Die Dokumentation/Tests wurde(n) aktualisiert.

# Tech-Spec

- Verwalter*innen in der `participation#show` view mit Email und Telefonnummer anzeigen (hitobito_youth)
- Verwalter*innen in export/pdf/participation anzeigen mit Email und Telefonnummer anzeigen (hitobito_jubla)
- Keine Anpassung von Rechten nötig

# ToDo

- [x] `app/views/person/managers/_list.html.haml` mit Email und Telefonnummer ergänzen (hitobito_youth)
- [x] `app/views/person/managers/_list.html.haml` so anpassen, dass Link auf Manager nur angezeigt wird, wenn man auch die Rechte auf diese Person hat (hitobito_youth)
- [x] `app/domain/jubla/export/pdf/participation.rb`  mit Abschnitt zu Verwaltern mit Email und Telefonnummer ergänzen (hitobito_jubla)
- [x] Specs schreiben
- [ ] Seeds für Anlassanmeldung mit Verwaltung ergänzen
- [x] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by richardjubla** [comment]
Nachträglich nach Hackathon nach Austausch im Youth Wagon: Der Nutzen wäre noch höher, wenn neben dem Namen auch noch die E-Mail-Adresse und Tel. Nr (falls vorhanden) in der Anmeldung angezeigt würde.

**Comment by diegosteiner** [comment]
@ThomasEllenberger 

Ich habe nun eine erste Version dieses Features umgesetzt und zum Code-Review bereitgestellt. Ein paar Bemerkungen zur Umsetzung:

- Ich habe die Anzeige der Anmeldung mit derselben Ansicht in hitobito_youth ergänzt, wie sie schon auf der Personenansicht war.
- Für beide Fälle habe ich jetzt zum Namen dazu auch noch die Hauptemail sowie die erste Telefonnummer genommen (ebenfalls in hitobito_youth). Das wiederum bedeutet, dass bei allen youth-Wagons neu diese beiden Informationen mit angezeigt werden. Es müssten also sicher alle betroffenen Kunden hierrüber informiert werden, da es Datenschutztechnisch schon relevant ist: ![image](https://github.com/user-attachments/assets/7fa82fbf-1b4e-4099-ad98-c2cff06a4903)
- Dasselbe habe ich für die Anmeldung im PDF gemacht, hier allerdings wie beschrieben nur im Jubla-Wagon: 
![image](https://github.com/user-attachments/assets/ad10bc35-48d4-476c-8747-0c9481893aac)
- Anpassungen der Rechte wurden **Keine** gemacht. Wenn eine Lagerleitung also die Verwalter*in nicht sehen kann, wird sie auch mit diese Feature keinen Zugriff haben, allerdings werden E-Mail und Telefonnummer nun immer in der Übersicht angezeigt

**Comment by richardjubla** [comment]
@diegosteiner 

Kannst du dir bitte das Feld "Schar:" genauer ansehen? Wir haben Rückmeldungen das hier (neu?) falsche Daten angezeigt werden. Eigentlich sollte es doch die ursprüngliche Schar oder die Schar anzeige, welche als "Hauptgruppe setzten" mit einem Stern im Profil versehen ist?

**Comment by diegosteiner** [comment]
Lieber @richardjubla 

Du beziehst dich hier auf das PDF, korrekt? Ich schaue mir das an, wäre aber noch froh, wenn du verifizieren könntest, dass das nichts mit der Migration auf Postgres zu tun hat. Sprich: ist es an anderen Stellen auch falsch? 

Danke!

**Comment by richardjubla** [comment]
> Lieber @richardjubla
> 
> Du beziehst dich hier auf das PDF, korrekt? Ich schaue mir das an, wäre aber noch froh, wenn du verifizieren könntest, dass das nichts mit der Migration auf Postgres zu tun hat. Sprich: ist es an anderen Stellen auch falsch?
> 
> Danke!

Sollte aus meiner Sicht nichts mit der Migration zu tun haben.

**Comment by diegosteiner** [comment]
> > Lieber [@richardjubla](https://github.com/richardjubla)
> > Du beziehst dich hier auf das PDF, korrekt? Ich schaue mir das an, wäre aber noch froh, wenn du verifizieren könntest, dass das nichts mit der Migration auf Postgres zu tun hat. Sprich: ist es an anderen Stellen auch falsch?
> > Danke!
> 
> Sollte aus meiner Sicht nichts mit der Migration zu tun haben.

Einverstanden, ich bin mir nur nicht sicher, woher das Problem kommen sollte. Im PDF habe ich nur neue Inhalte hinzugefügt, nichts bestehendes verändert. Die beiden Attribute `originating_flock` und `originating_state` sollten unverändert sein : https://github.com/hitobito/hitobito_jubla/pull/133/files

Kannst du mir einen Hinweis geben, wie du das getestet hast, damit ich das Problem nachvollziehen kann? Danke!

**Comment by richardjubla** [comment]
> Kannst du mir einen Hinweis geben, wie du das getestet hast, damit ich das Problem nachvollziehen kann? Danke!

Die Schar (originating_flock) und der dazugehörige Jublakanton (originating_state) sind eine Art "Herkunftsgruppe" eines Profils. Ich behaupte, dass es durch das zuteilen von Rollen und/oder das setzten der Hauptgruppe (Hauptgruppe setzen/pirmary_group) gesteuert wird. In diesem Kontext ist das Verhalten korrekt und nachvollziehbar.

Eine Zeit lang war das Setzen der Hauptgruppe defekt (https://github.com/hitobito/hitobito/issues/2365) es gibt also Profile, welche keine oder für sie eine nicht nachvollziehbare Hauptgruppe haben. Weiter gibt es Konstellationen in denen Menschen gar keiner Schar oder auch keinem Jublakanton zugehörig sind (Profile auf nationaler Ebene). Weiter gibt es Profile bei denen die Verbindung zu dieser Herkunftsgruppe "nur noch" über eine inaktive Rolle zugeteilt wird. 


**Definition:**
Ein Profil wird immer zu einer Jubla-Schar (originating_flock) und dem dazugehörigen Jubla-Kanton (originating_state) zugeteilt. Durch eine Rolle in der jeweiligen Schar (aktiv, inaktiv) oder durch das Setzen der Hauptgruppe im eigenen Profil. Bei Events werden diese Informationen angezeigt, um die Administration der Anmeldungen zu erleichtern. In Ausnahmefällen können diese Informationen veraltet oder fehlerhaft sein. 


Wenn die Definition "sinn" macht, ist der Kontext bekannt und somit "gelöst".

**Comment by richardjubla** [comment]
Zusammenfassung aus meiner Sicht:

- Erste Version dieses Features umgesetzt und zum Code-Review bereitgestellt. (Siehe https://github.com/hitobito/hitobito_jubla/issues/78#issuecomment-2404716101)
- `originating_flock` und `originating_state` sind geklärt oder bei der Abnahme zu testen (Wie sie sind, da keine anpassungen vorgenommen wurden)
-  Die Vorschau entspricht bis jetzt unseren Erwartungen

**Comment by rnestler** [comment]
@diegosteiner Soll hier der bereits gemergte PR reviewt werden?

**Comment by diegosteiner** [comment]
> @diegosteiner Soll hier der bereits gemergte PR reviewt werden?

@rnestler das ist wohl bereits erledigt, herzlichen Dank!

**Comment by richardjubla** [comment]
Auf der Stage-Umgebung nachvollziehbar: 
![image](https://github.com/user-attachments/assets/1c921641-0ad0-4ddc-8b41-2c1f24e05c06)

**Comment by richardjubla** [comment]
OK! Auf der Produktiver-Umgebung nachvollziehbar.
