### ISSUE TITLE
Selbstregistrierung: Formularfelder anpassen

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#79]
Dieses Feature folgt auf https://github.com/hitobito/hitobito_jubla/issues/75 und nimmt Bezug auf https://github.com/hitobito/hitobito_jubla/issues/75#issuecomment-1943303248

Als Verein (Schar/Gruppe/Ebene) bin ich verantwortlich für die mit mir interagierenden Menschen und deren Profile auf der Mitgliederdatenbank (jubla.db). Sofern ich eine Selbstregistrierung in meinen Verein (Schar/Gruppe/Ebene) anbiete, will ich bestimmte Informationen von den interagierenden Menschen abfragen, damit ich sie einfach(er) kontaktieren kann.

Neu sollen zusätzliche und angepasste (Pflicht)-Felder bei einer Selbstregistration ausfüllbar sein.

Bisher:
Bisher werden bei der Selbstregistration die folgenden Felder abgefragt:

Vorname (Pflichtfeld)
Nachname (Pflichtfeld)
Firmenname
Firma
Haupt-E-Mail
Datenschutzerklärung (Pflichtfeld)

Neu:
Neu sollen die folgenden Felder abgefragt werden:

Vorname (Pflichtfeld)
Nachname (Pflichtfeld)
Strasse / Nummer
PLZ/Ort
Telefonnummer (person_phone_numbers, lediglich eine Nummer, Informationen NICHT öffentlich: person_phone_numbers_attributes_0_public)
Haupt-E-Mail (Pflichtfeld)
Datenschutzerklärung (Pflichtfeld)

Nicht mehr angezeigt/abgefragt soll werden:

Firmenname
Firma

Akzeptanzkriterien:
- Es ist nicht möglich, durch Selbstregistrierung an Informationen oder Rechte zu kommen, die nicht öffentlich sind. Siehe: https://github.com/hitobito/hitobito/issues/2357
- Umsetzung nur im jubla-Wagon (individuell)
- Weiterentwicklungen wie https://github.com/hitobito/hitobito/issues/2404 natürlich weiterhin zulassen

# Mockup

![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/56ac7f14-28cf-40d0-bf0f-ddfc10ebf091)

# Tech-Spec

- sinngebende Zielrichtung
- besondere/bekannte Bedingungen und Grenzfälle
- technische Einschränkungen
- Ein- und Ausgabeformate beschreiben
- Umsetzungsplan ergänzen oder anpassen

# ToDo

- [x] Wizard anpassen
- [x] Specs schreiben
- [ ] Kunde wegen Übersetzungen informieren
- [x] Mit angemessener Rolle "durchklicken"
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by nchiapol** [comment]
Weshalb die Haupt-E-Mail bisher kein Pfilchtfeld ist war ist auch nicht klar - ganz ohne Kontaktangaben scheint eine Selbstregistrierung ziemlich sinnlos.

Gerade im Zusammenhang mit dem Elternzugang scheint mir aber eine Registration ohne Hauptmail nützlich. So können Eltern sich selbst und alle Kinder erfassen und der Adressverantwortliche der Schar muss sie nur noch verknüpfen. Wenn die Kinder auch eine Haupt-E-Mail brauchen, widerspricht das der Idee des Elternzugangs.
Allenfalls würde es aber Sinn machen bei einer Selbstregistration ohne Haupt-E-Mail noch ein Bestätigungs-Popup anzuzeigen.

Die Erweiterung um Adress- und Telefonfeld könnte gerne im Youth-Wagon umgesetzt werden.

**Comment by richardjubla** [comment]
> Weshalb die Haupt-E-Mail bisher kein Pfilchtfeld ist war ist auch nicht klar - ganz ohne Kontaktangaben scheint eine Selbstregistrierung ziemlich sinnlos.

![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/b4b71dda-e8e5-4d43-8634-fbe126906ba0)

In meiner Interpretation auch. Die Selbstregistration soll (und kann) aber die Funktion der Kind-Registrierung (für einen Event) als 2. Teil des Elternzugangs nicht konkurrenzieren oder ersetzten. (bei uns weiterhin nicht aktiv)
Gemäss unserer aktuellen Vorstellung sollen Eltern per Selbstregistration ihr Interesse bekunden und werden "manuell" von der Scharleitung mit besehenden oder erstellen Kinder-Profilen verknüpft. Siehe Anleitung: https://jubladb-handbuch.readthedocs.io/de/latest/profilverwalter.html 

Wir gewichten eine Haupt-E-Mail für ein Profil, Kommunikationsmöglichkeit und als Information für "wichtiger" (deshalb Pflichtfeld), als die Möglichkeit Profile ohne E-Mail-Adresse anzulegen. 
(Auch deshalb, weil das löschen von solchen Profilen auf Ebene Schar/Gruppe noch nicht selbständig vollzogen werden kann)

**Comment by richardjubla** [comment]
Bestandteil dieser Story/Offerte (aus #75 ) ist auch der Umstand, dass eine externe Registrierung mit Leserechten (auf Profile) oder mit Contact_Data Relevanz vergeben werden kann. https://github.com/hitobito/hitobito/issues/2357

Quickfix: Nur Leserechte für externe Registrierung (oder nur Rolle Versandadresse) 


Unter der Prämisse, dass eine externe Registrierung zwar zu einer Mitgliedschaft führt, aber einer ausdrücklichen Bearbeitung/Prüfung erfordert: Wir möchten verhindern, dass eine externe Registrierung zu Leserechten oder fehlender Sichtbarkeit/Verwaltbarkeit führt. Nach meiner Interpretation dürfen für die externe Registrierung demnach nur Rollen mit Leserechten möglich sein. (Beachten: Ist die Rolle Extern/Kind möglich, muss die Adressverwaltung in der gleichen Gruppe sein. Daher vielleicht diese Option auch ausschliessen)

**Comment by richardjubla** [comment]
@ThomasEllenberger 

Bitte diese Story im Kontext von https://github.com/hitobito/hitobito/issues/2641 abgleichen. Aus meiner Sicht wird damit unser Ziel auf Ebene "Core" vorbereitet und unser Wunsch (dieses Ticket) müsste den Teil in unserem Wagon abdecken.

**Comment by richardjubla** [comment]
Story um Strasse und Nummer ergänzt, da diese Felder neu aus dem Feld Adresse entstanden sind.

**Comment by richardjubla** [comment]
Info von @ThomasEllenberger 

> -jubla#79: Dies wurde meines Erachtens depriorisiert und das #2357 daraus extrahiert. Hier machen wir aktuell nichts weiter bis du uns wieder ein go gibst, was noch wie umgesetzt werden soll.

Ich sehe keinen direkten Zusammenhang zwischen dieser Story und [#2357](https://github.com/hitobito/hitobito/issues/2357)
Bitte mit mir klären, wozu ich ein "go" geben kann.

**Comment by TheWalkingLeek** [comment]
Hoi @richardjubla 
Ich habe gerade mit der Umsetzung begonnen. Bei den Adressenfeldern fehlt laut der aktuellen Spez noch die Felder "zusätzliche Adresszeile", "Postfach", & "Land". Ist es für dich ok wenn ich die noch dazu nehme? Das würde mir das Leben etwas erleichtern weil ich dann genau dasselbe Formular wie dauf der `person#edit` Seite wiederverwenden kann.

![Image](https://github.com/user-attachments/assets/468bd4f6-ed54-4eb4-b9f9-20ff4db7d3cf)

(Auf dem Screenshot fehlen noch ein paar Felder aber so sehen dann die Adressfelder aus. Wie gesagt dieselben wie im regulären Personenformular.)


Sag mir aber gerne falls diese Felder aber bewusst dort nicht angezeigt werden sollen.

**Comment by richardjubla** [comment]
> Hoi [@richardjubla](https://github.com/richardjubla) Ich habe gerade mit der Umsetzung begonnen. Bei den Adressenfeldern fehlt laut der aktuellen Spez noch die Felder "zusätzliche Adresszeile", "Postfach", & "Land". Ist es für dich ok wenn ich die noch dazu nehme? Das würde mir das Leben etwas erleichtern weil ich dann genau dasselbe Formular wie dauf der `person#edit` Seite wiederverwenden kann.
> 
> 
> (Auf dem Screenshot fehlen noch ein paar Felder aber so sehen dann die Adressfelder aus. Wie gesagt dieselben wie im regulären Personenformular.)
> 
> Sag mir aber gerne falls diese Felder aber bewusst dort nicht angezeigt werden sollen.

**Ja, so weiterverfolgen. Ich unterstütze den Hinweis von "erleichtern".** Es soll nach Möglichkeit zukünftige Arbeiten oder Anpassungen der Adressfelder gut mitmachen.  

(Gedanken: Es sind freiwillige Felder. Selbst das aus Jubla-Schar Sichtweise "komische" Feld Land kann übersprungen oder schnell ausgefüllt werden. Entgegen der UX-Empfehlung nur zwingende Felder abzufragen, soll die externe Selbstregistrierung auf freiwilliger Basis so viel wie möglich anbieten. )

**Comment by richardjubla** [comment]
@amaierhofer 

Bei einer Selbstregistrierung wird ein E-Mail mit dem Betreff "Anleitung für das Setzen Deines Passworts" versendet.

![Image](https://github.com/user-attachments/assets/6b77c000-7ffb-4617-83b6-e6c95ec987f9)

Diese E-Mail und der Text dazu kann nicht angepasst werden. Ist das korrekt?
