### ISSUE TITLE
Anpassungen von Rollen: FG-Mitglieder :contact_data-Flag entfernen

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#89]
Diese Story/Issue ersetzt den Teilbereich von Maintenance Package #50 für den Inkrement 2/24

Alle **Mitglieder von Fachgruppen** haben aktuell Kontaktrelevanz ([:contact_data](https://hitobito.readthedocs.io/de/latest/access_concept.html#spezialfall-contact-data)).
Da sie keine “Leitende” oder "Verantwortliche" Funktion haben (Scharleitung/Präsident/etc.) und auch nicht in einer Ebene/Gruppe mit “Leitender” Aufgabe sind (Kantonsleitung/Regionalleitung) ist nicht gerechtfertigt/schlüssig, dass sie Kontaktrelevanz besitzen.

Ausnahme: Einzig die Mitglieder von **Fachgruppen der nationalen Ebene** sollen (weiterhin) Kontaktrelevanz haben, da sie auch als Mitglieder dieser Fachgruppe gegenüber dem Verband auftreten und somit in diesem Kontext eine Vorstand-Aufgabe innehaben. Kurz: Mitglieder von nationalen Fachgruppen sollen sich als als kontaktrelevant markiert mit allen anderen Menschen mit kontaktrelevanten Rollen sehen und mit ihnen im Austausch stehen können. (Entscheid SG jubla.digital 20.4.23)

**Aspekte**

- Pull: https://github.com/hitobito/hitobito_jubla/pull/64
- Jubla Datenschutz https://jubladb-handbuch.readthedocs.io/de/latest/datenschutz.html
- Wer sieht meine Daten https://jubladb-handbuch.readthedocs.io/de/latest/anleitung.html#wer-sieht-meine-daten
- Spezialfall Contact_Data https://hitobito.readthedocs.io/de/latest/access_concept.html#spezialfall-contact-data

**Definition of Done**

- Die Berechtigung(en) :contact_data für die Rolle Mitglied in der Gruppe Fachgruppe ist entfernt.
- Die Berechtigung(en) :contact_data für die Rolle Mitglied in der Gruppe Fachgruppe in der Ebene Bund bleibt bestehen. (Beispiel: https://jubla.puzzle.ch/groups/480 )
- Unit Tests sind aktualisiert und entsprechen den gemachten Anpassungen

Interpretation der zukünftigen Jubla Organization Hierarchy für die Fachgruppen:

 * Bund
    * Fachgruppe
      * Leitung: [:group_full, **:contact_data**]
      * Mitglied: [**:contact_data**, :group_read]
      * Adressverwaltung: [:group_full]
      * Ehemalig: [:group_read]
      * Extern: []
      * Versandadresse: []
  * Kanton
    * Kanton
    * Fachgruppe
      * Leitung: [:group_full, :contact_data]
      * Mitglied: [~~:contact_data~~, :group_read]
      * Adressverwaltung: [:group_full]
      * Ehemalig: [:group_read]
      * Extern: []
      * Versandadresse: []
  * Region
    * Fachgruppe
      * Leitung: [:group_full, :contact_data]
      * Mitglied: [~~:contact_data~~, :group_read]
      * Adressverwaltung: [:group_full]
      * Ehemalig: [:group_read]
      * Extern: []
      * Versandadresse: []
  * Schar
  * Global
    * Fachgruppe
      * Leitung: [:group_full, :contact_data]
      * Mitglied: [~~:contact_data~~, :group_read]
      * Adressverwaltung: [:group_full]
      * Ehemalig: [:group_read]
      * Extern: []
      * Versandadresse: []
  * Kanton
    * Fachgruppe
      * Leitung: [:group_full, :contact_data]
      * Mitglied: [~~:contact_data~~, :group_read]
      * Adressverwaltung: [:group_full]
      * Ehemalig: [:group_read]
      * Extern: []
      * Versandadresse: []
  * Region
    * Region
    * Fachgruppe
      * Leitung: [:group_full, :contact_data]
      * Mitglied: [~~:contact_data~~, :group_read]
      * Adressverwaltung: [:group_full]
      * Ehemalig: [:group_read]
      * Extern: []
      * Versandadresse: []
  * Schar
  * Global
(Output of rake app:hitobito:roles)

![image](https://github.com/hitobito/hitobito_jubla/assets/95908537/8e9ff4e9-dc2a-44ed-bf9c-08b7ac0da3e1)

## ToDo

- [x] Rolle Fachgruppe/Mitglied anpassen
- [x] Specs anpassen oder hinzufügen (siehe hierzu auch #64)
- [x] Rollenübersicht im README aktualisieren
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by richardjubla** [comment]
Change auf produktivem System gengekommen. Aus unserer Sicht getestet und funktioniert gemäss Story.

**Comment by richardjubla** [comment]
Schliesse Story: Definition of Done wurde erfolgreich umgesetzt.
