### ISSUE TITLE
Neue Rolle(n) für ehemalige Jubla-Mitglieder / im Gruppentyp Ehemalige

### ISSUE THREAD

**Issue by richardjubla** [hitobito/hitobito_jubla#95]
**User-Story**

Als Vorstand der Gruppe [EhemaIige ](https://db.jubla.ch/groups/9435) (Verein) auf Ebene Bund* möchte ich als Vorstand (Leitung, Adressverwaltung, etc.) einem Profil neu Rolle(n) zuteilen können, um die direkte Zugehörigkeit zum NEJB abbilden zu können.
(*Ebene Bund = höchste Ebene und deren Untergruppen, FederalAlumnusGroup, NICHT Kanton, Region, Schar oder Global)

Neu soll es für die Gruppe/Ebene vom Typ Ehemalige auf der Ebene Bund folgende Rollen geben:

- Aktivmitglied NEJB: [:group_read]
- Passivmitglied NEJB : [:group_read]
- Kollektivmitglied NEJB: []

Das Aktivmitglied und Passivmitglied kann die anderen Profile in der Gruppe sehen (Lesen auf der Gruppe / :group_read). Das Kollektivmitglied kann nur öffentliche Daten (Gruppen, Anlässe und Abos; keine anderen Personen) sehen. Die Rolle Kollektivmitglied  ist ein Profil, welches für den Verein angelegt und idealerweise durch ihn verwaltet wird (von einem Menschen, der stellvertretend für diesen Verein dieses Profil verwalten muss) oder wird einem Profil (Menschen) zugeteilt welches stellvertretend (Verantwortlich) für die Kollektivmitgliedschaft ist.

**Neue Rollen für Ebene/Gruppe vom Typ Ehemalige auf ebene Bund:**

**Aktivmitglied NEJB**
Übliche Rolle für ein Profil/Mensch, der von NEJB Mitgliederversammlung als aktives Einzelmitglied aufgenommen wird. Der NEJB verwaltet seine Mitglieder in der von ihm zu verantwortenden Gruppen. (Nur auf Ebene Verband). NEJB verwaltet damit seine Aktivmitglieder auf Ebene Bund damit selbst. Aktivmitglieder sind berechtigt die Mitglieder in der gleichen Gruppe (Vereinsmitglieder) zu sehen (:group_read).

**Passivmitglied NEJB**
Übliche Rolle für ein Profil/Mensch, der auf lokaler Ebene aus der Schar ausgetreten ist und eine Passivmitgliedschaft in Netzwerk Ehemalige Jungwacht Blauring beantragt. NEJB verwaltet damit seine Mitglieder auf Ebene Bund. Passivmitglied sind berechtigt die Mitglieder in der gleichen Gruppe (Vereinsmitglieder) zu sehen (:group_read).

**Kollektivmitglied NEJB**
Übliche Rolle für ein Profil, welches als juristische Person konstituierte Ehemaligenvereinigungen, deren Zweck mit demjenigen von Netzwerk Ehemalige Jungwacht Blauring in den Grundzügen übereinstimmt und von der NEJB Mitgliederversammlung aufgenommen wurden. Der NEJB verwaltet seine Kollektivmitglieder auf nationaler Ebene. (Aktuell auf Ebene Verband).
NEJB verwaltet damit seine sich in der nationalen Gruppe NEJB Kollektivmitglieder befindenden Mitglieder.

Aspekte:

- Natürliche Personen können nur dann Mitglied werden, wenn sie Ehemalige Jungwacht Blauring sind, also auf lokaler Ebene aus einer Schar ausgetreten sind und den Vereinszweck unterstützen. (gemäss technischer Einschränkung der jubla.db UND den Bestimmungen in den Statuten des NEJB)
- In der jubla.db kann ein Profil nicht Aktive Rollen haben UND Mitglied ehemalig sein. [→ ](https://github.com/hitobito/hitobito_jubla/blob/817669294a6da91a9794f970462d158f19af8478/spec/models/role_spec.rb#L189C14-L189C114) - Die neue Rolle(n) können auch für Profile mit aktiven Rollen zugeteilt werden. 

**Definition of Done**
- Neue Rolle(n) in der jubla.db anwendbar
- Tests/Berechtigungen/etc. auf Seiten Hitobito abgedeckt
- Rollen-Beschrieb aktualisiert

**Vorschlag für Test/Abnahme**

- [ ]  In der Gruppe “Ehemalige” auf Ebene Bund können die neuen Rollen vergeben werden. (https://jubla.puzzle.ch/groups/330)
Aktivmitglied NEJB
Passivmitglied NEJB
Kollektivmitglied NEJB
- [ ]  Die Rolle(n) der Gruppen/Ebenen “Ehemalige” sind im Profil sichtbar und nachvollziehbar. Test: [Schwarze Jrgen / Ehemalig](https://jubla.puzzle.ch/groups/330/people/1242) ist Mitglied im [NEJB](https://jubla.puzzle.ch/groups/330/people?returning=true) ([Bug](https://github.com/hitobito/hitobito_jubla/issues/53): aktuell in seinem Profil nicht sichtbar!)
Das Entfernen der neuen Rollen führt nicht dazu, dass das die Rolle “Ehemalig” vergeben wird oder das Profil in einer Gruppe “Ehemalige” eine neue Rolle bekommt. Test: Neue Rolle einem Profil nach acht Tagen wieder entfernen.
- [ ]  In der Untergruppe vom Typ “Ehemalige” können Rollen vergeben werden. Test: Rollen in [Untergruppe](https://jubla.puzzle.ch/groups/487/people?returning=true) zuweisen
- [ ]  Auf darunterliegenden Ebenen (Kanton/Region/Schar) können die neuen Rolle nicht vergeben werden. Test: Vergeblich versuchen, [hier](https://jubla.puzzle.ch/groups/297/people?returning=true) die neuen Rollen zu vergeben.
- [ ]  Die neuen Rollen können nur dann vergeben werden, wenn auf lokaler Ebene keine (aktiven) Rollen mehr vorhanden sind. Ein Profil kann aber explizit und neu auf Ebene Bund/Kanton/Region aktive Rollen haben. Test: Profil ([Ekaterina Reinhold](https://jubla.puzzle.ch/groups/297/people/1241)) mit Mitglied in Gruppe Ehemalig auf ebene Schar UND auch einer Rolle auf Ebene Bund/Kanton/Region die neuen Rollen zuweisen.[Celine Ritz](https://jubla.puzzle.ch/groups/296/people/1375) kann nicht eine NEJB-Rollen erhalten, weil sie noch aktiv in einer Schar ist.

# ToDo

- [ ] Issue für Umsetzung erstellen
- [ ] Workflow des Features beschreiben
- [ ] ggf. Mockup erstellen
- [ ] Tech-Spec ergänzen
- [ ] ToDo für Umsetzung definieren

```
**Neue Interpretation: Jubla Organization Hierarchy**

  * Bund
    * Bund
      * Adressverwaltung: [:group_full]
      * Ehemalig: [:group_read]
  * Bund
    * Bund
    * Bundesleitung
    * Verbandsleitung
    * Fachgruppe
    * Arbeitsgruppe
    * Ehemalige
      * Leitung: [:group_and_below_full, :contact_data, :alumnus_below_full]
      * Adressverwaltung: [:group_and_below_full]
      * Kassier/in: [:group_and_below_read]
      * Aktivmitglied NEJB: [:group_read] 🆕
      * Passivmitglied NEJB: [:group_read]🆕
      * Kollektivmitglied NEJB: []🆕
      * Mitglied: [:group_read]
      * Extern: []
      * Versandadresse: []
  * Kanton
    * Kanton
  * Region
    * Region
  * Schar
    * Schar
  * Global
    * Einfache Gruppe
    * Bundesleitung
    * Verbandsleitung
    * Fachgruppe
    * Arbeitsgruppe
    * Ehemalige
  * Kanton
    * Kanton
  * Region
    * Region
  * Schar
    * Schar
  * Global
    * Einfache Gruppe
```

**Comment by richardjubla** [comment]
Basierend auf der Sitzung der PG Ehemaligenwesen (27.06.24) wird diese Story geschlossen (vertagt). Es folgt ein Plan und konkrete Stories im Inkrement 3/24 in der diese Story vielleicht in abgeänderter Form aufgegriffen wird.
